generateMode/CopyData
thulab/iotdb-benchmark pull request #231
Opened 2021-12-17 16:14 UTC by LittleHealth

Add one generating mode for series: copy data, which means copy real data source(.csv) and insert anomalies to get a very long pseudo-real time series.

2021-12-18 07:18 UTC, stormbroken requested changes

2021-12-18 07:18 UTC, stormbroken commented on core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/source/CopyDataReader.java
> +package cn.edu.tsinghua.iotdb.benchmark.source;
you need to add license in new file

2021-12-18 07:18 UTC, stormbroken commented
Thanks for your contribution, excellent job!
From my perspective, I have some suggestions.
1. Firstly, I think you can add some doc about how to use these parameters, and you can add them into README.md and README-cn.md for other users who may need these features.
2. Secondly, I want to know  what is the main difference between isIS_COPY_MODE = false and isIS_COPY_MODE = true? From my perspective, now you implementation looks like just do some changes on the data from the csv file, I think you can specific this thing in the doc for other user to choose which one to use. Related things are as follows, how many batch in one file, difference between the timestamp  in the file and and the timestamp finally written into database, difference between the value in the file and the value finally written into database.

2021-12-30 07:54 UTC, LittleHealth commented on core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/source/CopyDataReader.java
> +package cn.edu.tsinghua.iotdb.benchmark.source;
done! Thanks

2021-12-30 08:19 UTC, stormbroken approved these changes
LGTM

2022-01-05 07:22 UTC, merged